spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sa
    driverClassname: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          pool_size: 30
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:

  api-docs:
    path: /api-docs

  show-actuator: true

  swagger-ui:
    show-extensions: true
    operations-sorter: method

server:
  port: 8080